# This file configures the behavior of tool/htmlgen.dart.

output_directory = 'build/text'
output_images_subdirectory = 'imgs'

# Where to get *.md files from. This is probably an absolute path
# into your Obsidian vault or something similar.
markdown_directory = '/Users/filiph/Google Drive/notes/memex/projects/filiphnet'

# When markdown files reference images, where do we go find them?
# This is probably an absolute path to the place where Obsidian stores
# images.
images_directory = '/Users/filiph/Google Drive/notes/memex/images'

# The HTML file with the structure of the page, and special strings
# that serve as placeholders.
page_template = 'src/page.template.html'

# Markdown file to render and place at the end of each article.
# This is probably a bit of info about the author and possibly a 'what next'
# message (such as "go wishlist my game on Steam").
footer_markdown_path = 'src/page_footer.md'
